# -*- coding: utf-8 -*-
"""1_Carga_datos.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1hy1nP7CwB-AzqIlVUcziDH0jjkHCTQaZ

# **Proyecto Final Unidad 6 Metodologias Agiles para Proyectos de Machine Learning**
---
##**Presentado por**:  
# Daniel Cardozo

##**Tema**:
# **Aplicación de Deep Learning para la Interpretacion Clínica de Pruebas de Sensibilidad Antimicrobiana (SIR)**

## **1.2. Datos**
---

En esta sección debe adjuntar una descripción de los datos y agregar el código que permite su tratamiento.

### **1.2.1. Origen**
---

###- ¿De dónde vienen los datos?

Los datos se obtendrán de las **Bases de Datos de Whonet** de una Institución de Salud de reporte obligatorio al ministerio de salud de forma mensual, del periodo comprendido entre 2019 a mayo de 2025 para un tamaño aproximado de 50.000 registros.

###- ¿Se usa alguna herramienta o proceso para la descarga de la información?

En nuestro, los datos se obtienen de un sistema automatizado para la identificación de microbiológica de bioMérieux, el cual genera datos sobre la identificación de bacterias y su sensibilidad a los antibióticos. Estos datos pueden ser exportados en diferentes formatos, como CSV o archivos de texto para su posterior análisis.

###- ¿Qué tipo de datos estamos manejando?

Se utiliza bases de datos en formato .sir, la cual contiene  datos de pacientes y resultados de cultivos en diferentes muestras.

### **1.2.2. Carga o Adquisición de Datos**
---

Agregue el código necesario en _Python_ para obtener o cargar los datos.
"""

import pandas as pd
import numpy as np

"""### *Base de Datos Microorganismos Aislados*"""

from google.colab import files
uploaded = files.upload()

#para facilitar la lectura de la informacion, los archivos en formato .sir se guardan en formato .xlsx
bd_whonet = pd.read_excel('Clinicas_2019_2025.xlsx')

#Mostramos informacion del Dataframe
bd_whonet.info()

#mostramos columnas
bd_whonet.columns

#Describimos la base de datos de whonet
bd_whonet.describe()

#Eliminamos algunas columnas de la base de datos porque contienen informacion de pacientesb
bd_whonet= bd_whonet.drop(['COUNTRY_A','ORIGIN','INSTITUT','LABORATORY', 'LAST_NAME', 'FIRST_NAME', 'DATE_BIRTH'], axis=1)
bd_whonet = bd_whonet.dropna(how='all') #Borrar columnas vacias
print(bd_whonet.columns)
print(bd_whonet.shape)

#Mostramos primeras 10 filas
bd_whonet.head(10)

"""### *Base de Datos de Etiquetas*"""

from google.colab import files
uploaded = files.upload()

# Cargamos la informacion de Etiquetas para cada atb
bd_SIR = pd.read_excel('SIR_2019_2025.xlsx')

#Mostramos informacion del Dataframe
bd_SIR.info()

#mostramos columnas
bd_SIR.columns

#Describimos la base de datos de whonet
bd_SIR.describe()

#Eliminamos algunas columnas de la base de datos porque contienen informacion de pacientesb
bd_SIR= bd_SIR.drop(['INSTITUT'], axis=1)
bd_SIR = bd_SIR.dropna(how='all') #Borrar columnas vacias
print(bd_SIR.columns)
print(bd_SIR.shape)

#Mostrar primeras 10 filas y 20 primeras columnas
bd_SIR.head(10)